[build]
  functions = "functions"

[[redirects]]
  from ="/profile/:id"
  to = "/.netlify/functions/profile?id=:id"
  status= 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"